### ISSUE TITLE
A Termimal flasing whenever opening or closing the result .exe

### ISSUE THREAD

**Issue by alexshcer** [SerGreen/Appacker#16]
When ever i am opening the app created by appacker first a terminal flash then it start same happen when closing the app

**Comment by SerGreen** [comment]
That's normal. Terminal that you see is a console application that performs unpacking into a temp folder and then launches the unpacked target application. This console app is set up to hide itself right away, but it still results in it being visible for a split-second.  
When the target app is closed this console tool checks if any files were changed and performs re-packing if needed.

**Comment by alexshcer** [comment]
Yes, but is there any way of hiding the terminal

**Comment by SerGreen** [comment]
Unfortunately i didn't find a way for that.  

It should be noted, however, that terminal **was** completely hidden before (v1.3.3 and earlier) because back then it was a windowless program (compared to terminal program that hides itself currently). I changed it to terminal because a windowless program can't redirect its I/O and it interfered with launching packed applications from command line.  
So one option for you would be to use [v1.3.3](https://github.com/SerGreen/Appacker/releases/tag/v1.3.3), however, it's 3 years old and is missing all the features and fixes of newer versions.  

I'll see if i will be able to add a window-less package as an option for the next version of Appacker.

**Comment by alexshcer** [comment]
Ok
