### ISSUE TITLE
Select save location for the package (it is NOT an .exe file).

### ISSUE THREAD

**Issue by redstoneleo** [SerGreen/Appacker#18]
![image](https://user-images.githubusercontent.com/5896180/162564280-bb5d3236-443d-49f8-89fe-ab66f36003e2.png)

As for 
`Select save location for the package (it must be an .exe file).`
The dialog filter restricts only exe files are selectable, but what actually expects here is a path, so please correct the problem.

**Comment by SerGreen** [comment]
This field asks you for the name (and location) of the resulting package, and packed application will always be generated as *.exe file - that's why there's a filter for extension. It doesn't depend on the extension of the source application that is being packed.  

Normally you don't want to select an existing *.exe file in this window, because it would overwrite that file then. Usually you want to create a new file instead, so you have to open a directory where you want to save the package, give this file a unique name and click 'Save'. Extension will be appended automatically.

**Comment by redstoneleo** [comment]
So I'd suggest changing the current description to `Please specify the name (and location) of the resulting package` to get rid of the confusion.

BTW, I reported another issue -->https://github.com/SerGreen/Appacker/issues/17#issuecomment-1093834833
