### ISSUE TITLE
Possibility of Password Protection?

### ISSUE THREAD

**Issue by P0stmaster** [SerGreen/Appacker#19]
Hello SerGreen, 

I love the software, just wondering if there was a way to implement password protection?

**Comment by SerGreen** [comment]
You mean so that it would ask for a password when you try to launch a packed application? Yeah, i think there could be an option for that, it could store a hash of the password within the package or something, and then have a simple password prompt before unpacking the app. Not super secure but enough for simple use cases. I'll add it to the list of requested features.

**Comment by P0stmaster** [comment]
Exactly! I'd like to have the option to unpack, thank you for the quick response. I can't find any other software that's as good as yours so I'd figure I'd ask. Thank you SerGreen

**Comment by SerGreen** [comment]
Done and now available in [v1.3.11](https://github.com/SerGreen/Appacker/releases/tag/v1.3.11).
